apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |-
    user  root;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  102400;
    }
        
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
       
        ssi on;
        ssi_silent_errors off;
        ssi_types text/shtml/html;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
      
        #websocket代理配置
        map $http_upgrade $connection_upgrade {
           default upgrade;
           '' close;
        }       

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;
    server {
    listen       80;
    server_name  _;

        include /etc/nginx/conf.d/*.conf;
    }
