apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-log
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  storageClassName: nginx-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ NginxLogDataPath }}
    server: {{ LogStorageAddr }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-web
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  storageClassName: nginx-pv-web-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ NginxDataPath }}
    server: {{ DataStorageAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-config
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  storageClassName: nginx-pv-config-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ NginxConfigDataPath }}
    server: {{ DataStorageAddr }}
### 20210202   ###
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-mcndata
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  storageClassName: nginx-pv-mcndata-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ NginxMCNDataPath }}
    server: {{ DataStorageAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-wcmdata
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  storageClassName: nginx-pv-wcmdata-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ NginxWCMDataPath }}
    server: {{ DataStorageAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-wcmpublishdata
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  storageClassName: nginx-pv-wcmpublishdata-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ NginxWCMPublishDataPath }}
    server: {{ DataStorageAddr }}
