# Source: dicttool/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dicttool-deploy
  labels:
    app: dicttool
    chart: "dicttool-1.0.0"
    release: "dicttool"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dicttool
      release: "dicttool"
  template:
    metadata:
      labels:
        app: dicttool
        release: "dicttool"
    spec:
     # nodeSelector:
     #   kubernetes.io/hostname: 192.168.200.94
      volumes:
      - name: dicttool-pvc-log
        persistentVolumeClaim:
          claimName: dicttool-pvc-log
     # hostAliases:
     # - ip: "10.6.42.1"
     #   hostnames:
     #   - "nginx.nyrb-test.com"
      containers:
      - name: dicttool
        image: {{ DicttoolImage }}
        envFrom:
        - configMapRef:
            name: mcb-dicttool-configmap
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /TRS/DATA/dicttool/logs
          name: dicttool-pvc-log
        ports:
          - name: http
            containerPort: 8090
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
