apiVersion: v1
kind: ConfigMap
metadata:
  name: mcb-dicttool-configmaps
data:
  # 类属性键；每一个键都映射到一个简单的值
# 大数据应用公有变量
  spring.datasource.url: "jdbc:mysql://mariadb-svc:3306/mcb_dicttool"
  spring.datasource.username: "mcbdicttool"
  spring.datasource.password: "{{ DicttoolDBPassword }}"
  spring.cloud.nacos.config.namespace: "8953ca45-4cfb-469a-bc55-7e3bce569994"
  spring.cloud.nacos.config.server-addr: "nacos-svc:8848"
  spring.cloud.nacos.discovery.server-addr: "nacos-svc:8848"
  hybase.database.url: "hybase-svc"
  hybase.database.port: "5555"
  hybase.database.user: "admin"
  hybase.database.password: "hiWjOXrAM6kpsOtA"
  spring.kafka.bootstrap-servers: "kafka-svc"
  spring.redis.masterName: "mymaster"
  spring.redis.nodes: "redis-ha-announce-0:26379,redis-ha-announce-1:26379,redis-ha-announce-2:26379"
  spring.redis.pwd: "{{ TRSRedisPassword }}"
  ckm.database.url: "ckm-svc"
  ckm.database.password: "trsadmin"
# mcb_dicttool 特有变量
  spring.redis.sentinel.master: "mymaster"
  spring.redis.sentinel.nodes: "redis-ha-announce-0:26379,redis-ha-announce-1:26379,redis-ha-announce-2:26379"
  spring.redis.password: "{{ TRSRedisPassword }}"
  spring.redis.database: "3"
