apiVersion: v1
kind: Service
metadata:
  name: callback-svc
  labels:
    app: callback
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: callback
