apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interaction-task-pvc-log
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: interaction-task-pv-log-class
  resources:
     requests:
       storage: 200Gi
