apiVersion: v1
kind: Service
metadata:
  name: mcnadmin-svc
  labels:
    app: mcnadmin
spec:
  type: ClusterIP
  ports:
    - port: 9002
      targetPort: 9002
      protocol: TCP
      name: http
  selector:
    app: mcnadmin
