apiVersion: v1
kind: ConfigMap
metadata:
  name: mcnadmin-configmap
data:
  # 类属性键；每一个键都映射到一个简单的值
# 大数据应用公有变量
  protocol.http.url: "http://nginx-svc/ids/protocol"
  idm.server.host: "trsids-svc"
  idm.server.port: "2005"
  cookie.domain: "trsids-svc"
  afterLoginOk.gotoUrl: "http://hk.cannews.com.cn/mcnadmin/web/user/ids.do"
  spring.datasource.main.url: "jdbc:mysql://mariadb-svc:3306/mcn_upc?useUnicode=true&characterEncoding=utf-8&useSSL=false"
  spring.datasource.main.username: "mcnadmin"
  spring.datasource.main.password: "{{ UPCAdminDBPassword }}"
  spring.datasource.tenant.url: "jdbc:mysql://mariadb-svc:3306/mcn_upc_mty?useUnicode=true&characterEncoding=utf-8&useSSL=false"
  spring.datasource.tenant.username: "mcnadmin"
  spring.datasource.tenant.password: "{{ UPCAdminDBPassword }}"
  spring.datasource.scheduler.url: "jdbc:mysql://mariadb-svc:3306/mcn_upc_quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false"
  spring.datasource.scheduler.username: "mcnadmin"
  spring.datasource.scheduler.password: "{{ UPCAdminDBPassword }}"
  spring.datasource.mrs.url: "jdbc:mysql://mariadb-svc:3306/mty_mrs?useUnicode=true&characterEncoding=utf-8&useSSL=false"
  spring.datasource.mrs.username: "mcnadmin"
  spring.datasource.mrs.password: "{{ UPCAdminDBPassword }}"
  spring.redis.host: "redis-svc"
  spring.redis.port: "6379"
  spring.redis.password: "{{ UPCAdminRedisPassword }}"
