---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picturecenter-pvc-data
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: picturecenter-pv-data-class
  resources:
     requests:
       storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picturecenter-pvc-log
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: picturecenter-pv-log-class
  resources:
     requests:
       storage: 300Gi
