apiVersion: v1
kind: Service
metadata:
  name: ddc-svc
  labels:
    app: ddc
spec:
  type: ClusterIP
  ports:
    - port: 9016
      targetPort: 9016
      protocol: TCP
      name: http
  selector:
    app: ddc
