apiVersion: v1
kind: Service
metadata:
  name: ddc-svc
  labels:
    app: ddc
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: 9998
      protocol: TCP
      name: http
  selector:
    app: ddc
