apiVersion: v1
kind: PersistentVolume
metadata:
  name: wcm-bigscreen-server-pv-data
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: wcm-bigscreen-server-data-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ WCMBigScreenServerDataPath }}
    server: {{ NFSAddr }}

