---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gather-consumer-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName:  gather-consumer-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ DataGatherLogPath }}
    server: {{ LogStorageAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gather-consumer-pv-data
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName:  gather-consumer-pv-data-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ DataGatherDataPath }}
    server: {{ DataStorageAddr }}

