---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gather-consumer-pvc-log
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: gather-consumer-pv-log-class
  resources:
     requests:
       storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gather-consumer-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: gather-consumer-pv-data-class
  resources:
     requests:
       storage: 1000Gi
