apiVersion: v1
kind: ConfigMap
metadata:
  name: tmyimgcenter-configmap
data:
  # 类属性键；每一个键都映射到一个简单的值
# 大数据应用公有变量
  server.port: "9004"
  spring.datasource.primary.url: "jdbc:mysql://mariadb-svc:3306/{{ DownImgDBName }}?useUnicode=true&characterEncoding=utf-8&useSSL=false"
  spring.datasource.primary.username: "{{ DownImgDBUser }}"
  spring.datasource.primary.password: "{{ DownImgDBPassword }}"
  spring.datasource.second.url: "jdbc:mysql://mariadb-svc:3306/{{ DownImgDBName }}?useUnicode=true&characterEncoding=utf-8&useSSL=false"
  spring.datasource.second.username: "{{ DownImgDBUser }}"
  spring.datasource.second.password: "{{ DownImgDBPassword }}"
