apiVersion: v1
kind: Service
metadata:
  name: tmyimgcenter-svc
  labels:
    app: tmyimgcenter
spec:
  type: ClusterIP
  ports:
    - port: 9004
      targetPort: 9004
      protocol: TCP
      name: http
  selector:
    app: tmyimgcenter
