---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-pvc-log
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: resource-pv-log-class
  resources:
     requests:
       storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-pvc-data
  namespace: sly
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: resource-pv-data-class
  resources:
     requests:
       storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-pvc-mediadata
  namespace: sly
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: resource-pv-mediadata-class
  resources:
     requests:
       storage: 200Gi
