---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: resource-pv-log
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: resource-pv-log-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ ResourceLogPath }}
    server: {{ LogStorageAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: resource-pv-data
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: resource-pv-data-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ ResourceDataPath }}
    server: {{ DataStorageAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: resource-pv-mediadata
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: resource-pv-mediadata-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ ResourceMediaDataPath }}
    server: {{ DataStorageAddr }}
