---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcn-pvc-log
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: mcn-pv-log-class
  resources:
     requests:
       storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcn-pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: mcn-pv-data-class
  resources:
     requests:
       storage: 1000Gi
