---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: newmediaplatform-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: newmediaplatform-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ NewMediaPlatformLogPath }}
    server: {{ NFSAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: newmediaplatform-pv-data
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: newmediaplatform-pv-data-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ NewMediaPlatformDataPath }}
    server: {{ NFSAddr }}
