apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nacostool-data-new
spec: 
  capacity: 
    storage: 50Gi
  volumeMode: Filesystem
  storageClassName: nacostool-data-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ NacosDataPath }}
    server: {{ DataStorageAddr }}

