apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nacostool-data-new
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: nacostool-data-class
  resources:
     requests:
       storage: 50Gi

