apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: push-syn-pvc-log
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: push-syn-pv-log-class
  resources:
     requests:
       storage: 1000Gi
