---
# Source: webcollection/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: webcollection-svc
  labels:
    app: webcollection
spec:
  type: ClusterIP
  ports:
    - port: 7176
      targetPort: 7176
      protocol: TCP
      name: http
  selector:
    app: webcollection
