apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-svc
spec:
  ports:
  - name: port-1
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: port-2
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch-master
    release: elasticsearch
  type: NodePort