---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcb-pm-pv-log
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: mcb-pm-pv-log-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ MCBPMLogPath }}
    server: {{ NFSAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcb-pm-pv-data
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: mcb-pm-pv-data-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ MCBPMDataPath }}
    server: {{ NFSAddr }}
