---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcb-pm-pvc-log
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: mcb-pm-pv-log-class
  resources:
     requests:
       storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcb-pm-pvc-data
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: mcb-pm-pv-data-class
  resources:
     requests:
       storage: 200Gi
