---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcnadmin-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: mcnadmin-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ MCNAdminLogPath }}
    server: {{ LogStorageAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcnadmin-pv-data
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: mcnadmin-pv-data-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ MCNAdminDataPath }}
    server: {{ DataStorageAddr }}
