apiVersion: v1
kind: Service
metadata:
  name: paperreview-svc
  labels:
    app: paperreview
spec:
  type: NodePort
  ports:
  - port: 9023
    targetPort: 9023
    protocol: TCP
    name: http
    nodePort: 39023
  selector:
    app: paperreview
