apiVersion: v1
kind: ConfigMap
metadata:
  name: paperreview-configmap
data:
  # 类属性键；每一个键都映射到一个简单的值
# 大数据应用公有变量
  spring.application.name: "paperreview"
  spring.cloud.nacos.config.server-addr: "nacos-svc:8848" 
  spring.cloud.nacos.config.namespace: "8953ca45-4cfb-469a-bc55-7e3bce569994"
  management.endpoints.web.exposure.include: "*"
  spring.cloud.nacos.config.prefix: "paperreview"
  spring.cloud.nacos.config.file-extension: "properties"
  spring.cloud.nacos.config.refreshable-dataids: "paperreview.properties"
  spring.cloud.nacos.discovery.server-addr: "nacos-svc:8848"
  server.port: "9023"
  server.servlet.context-path: "/paperreview"
  spring.datasource.url: "jdbc:mysql://mariadb-svc:3306/mty_wcm?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8"
  spring.datasource.username: "mtywcm"
  spring.datasource.password: "{{ PaperReviewDBPassword }}"
  spring.redis.masterName: ""
  spring.redis.nodes: "redis-svc:6379"
  spring.redis.pwd: "{{ PaperReviewRedisPassword }}"
  paperreview.layoutlist.forward.url: "http://nginx-svc/zyzx/epaper/getBmList"
  paperreview.layoutmenu.forward.url: "http://nginx-svc/zyzx/epaper/getBmMenu"
  paperreview.paperdetails.forward.url: "http://nginx-svc/zyzx/epaper/getBmDetail"
  paperreview.articleDetail.forward.url: "http://nginx-svc/zyzx/epaper/epaperDetail"
  paperreview.layoutpagetime.forward.url: "http://nginx-svc/zyzx/epaper/getPaperTime"
  paperreview.detailData.forward.url: "http://nginx-svc/zyzx/jtcpg/detailData"
  paperreview.caibian.permission.url: "http://nginx-svc/wcm/resource/right.action"
