---
# Source: resource/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-deploy
  labels:
    app: resource
    chart: "resource-1.0.0"
    release: "resource"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource
      release: "resource"
  template:
    metadata:
      labels:
        app: resource
        release: "resource"
    spec:
#      nodeSelector:
#        kubernetes.io/hostname: 192.168.200.94
      volumes:
      - name: pvc-resource-log
        persistentVolumeClaim:
          claimName: resource-pvc-log
      - name: pvc-resource-data
        persistentVolumeClaim:
          claimName: resource-pvc-data
      - name: pvc-resource-mediadata
        persistentVolumeClaim:
          claimName: resource-pvc-mediadata
#      hostAliases:
#      - ip: "10.6.42.1"
#        hostnames:
#        - "nginx.nyrb-test.com"
      containers:
      - name: resource
        image: {{ ResourceImage }}
        #image: registry.cn-hangzhou.aliyuncs.com/trssly/resource:v1
        envFrom:
        - configMapRef:
            name: resource-configmap
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /TRS/DATA/resource/logs
          name: pvc-resource-log
        - mountPath: /TRS/CONFIG/resource/
          name: pvc-resource-data
        - mountPath: /TRS/DATA/media_resource_data
          name: pvc-resource-mediadata
        ports:
          - name: http
            containerPort: 6083
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 360
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 360
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi

