apiVersion: v1
kind: ConfigMap
metadata:
  name: tenantcenter-configmap
data:
  # 类属性键；每一个键都映射到一个简单的值
# 大数据应用公有变量
  spring.application.name: "tenantcenter"
  spring.cloud.nacos.config.server-addr: "nacos-svc:8848"
  management.endpoints.web.exposure.include: "*"
  spring.cloud.nacos.config.prefix: "tenantcenter"
  spring.cloud.nacos.config.file-extension: "properties"
  spring.cloud.nacos.config.refreshable-dataids: "tenantcenter.properties"
  spring.cloud.nacos.discovery.server-addr: "nacos-svc:8848"
  spring.datasource.url: "jdbc:mysql://mariadb-svc:3306/mty_wcm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong"
  spring.datasource.username: "mtywcm"
  spring.datasource.password: "{{ TenantCenterDBPassword }}"
