apiVersion: v1
kind: Service
metadata:
  name: tenantcenter-svc
  labels:
    app: tenantcenter
spec:
  type: ClusterIP
  ports:
  - port: 9006
    targetPort: 9006
    protocol: TCP
    name: http
  selector:
    app: tenantcenter
