---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wcmdata-slytest
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: wcmdata-class-slytest
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ TRSWCMDataPath }}
    server: {{ DataStorageAddr }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wcmlog-slytest
spec: 
  capacity: 
    storage: 500Gi
  volumeMode: Filesystem
  storageClassName: wcmlog-class-slytest
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ TRSWCMLogPath }}
    server: {{ LogStorageAddr }}
