apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wcmdata-slytest
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: wcmdata-class-slytest
  resources:
     requests:
       storage: 1000Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wcmlog-slytest
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: wcmlog-class-slytest
  resources:
     requests:
       storage: 500Gi
