# Source: wcm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcm-deploy
  labels:
    app: wcm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcm
  template:
    metadata:
      labels:
        app: wcm
    spec:
      hostAliases:
      - ip: "192.168.200.99"
        hostnames:
        - "sly.trscd.com.cn"
      volumes:
      - name: pvc-wcmdata
        persistentVolumeClaim:
          claimName: pvc-wcmdata-slytest
      - name: pvc-wcmlog
        persistentVolumeClaim:
          claimName: pvc-wcmlog-slytest
      #- name: pvc-webapps
      #  persistentVolumeClaim:
      #    claimName: pvc-webapps
      containers:
        - name: wcm
          #image: registry.cn-hangzhou.aliyuncs.com/trssly/wcm:2.22.14-jindie
          image: {{ TRSWCMImage }}
          #image: registry.cn-hangzhou.aliyuncs.com/trssly/wcm:v9-null
          envFrom:
             - configMapRef:
                 name: trs-wcm-configmap
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /TRS/DATA
            name: pvc-wcmdata
          - mountPath: /TRS/TRSWCM/logs/
            name: pvc-wcmlog
          #- mountPath: /TRS/TRSWCM/webapps
          #  name: pvc-webapps
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
