# Source: wcm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcm-deploy
  labels:
    app: wcm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcm
  template:
    metadata:
      labels:
        app: wcm
    spec:
      volumes:
      - name: pvc-wcmdata
        persistentVolumeClaim:
          claimName: pvc-wcmdata-slytest
      - name: pvc-wcmlog
        persistentVolumeClaim:
          claimName: pvc-wcmlog-slytest
      containers:
        - name: wcm
          image: registry.cn-hangzhou.aliyuncs.com/trssly/wcm:v6
          envFrom:
             - configMapRef:
                 name: trs-wcm-configmap
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /TRS/DATA/WCMData/
            name: pvc-wcmdata
          - mountPath: /TRS/TRSWCM/logs/
            name: pvc-wcmlog
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
