apiVersion: v1
kind: ConfigMap
metadata:
  name: dshare-configmap
data:
  spring.datasource.url: "jdbc:mysql://mariadb-svc:3306/mty_dshare?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC"
  spring.datasource.username: "dshare"
  spring.datasource.password: "{{ DshareDBPassword }}"
  env.conf.mtyDomain: "http://hk.cannews.com.cn/dshare"
