apiVersion: v1
kind: PersistentVolume
metadata:
  name: propagation-server-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: propagation-server-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ PropagationServerLogPath }}
    server: {{ LogStorageAddr }}

