apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-data
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  storageClassName: redis-pv-data-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ RedisDataPath }}
    server: {{ DataStorageAddr }}
