apiVersion: v1
kind: Service
metadata:
  name: mlfsearch-svc
  labels:
    app: mlfsearch
spec:
  type: ClusterIP
  ports:
    - port: 9009
      targetPort: 9009
      protocol: TCP
      name: http
  selector:
    app: mlfsearch
