---
# Source: transfer-resource-ai/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: transfer-resource-ai-svc
  labels:
    app: transfer-resource-ai
    chart: "transfer-resource-ai-1.0.0"
    release: "transfer-resource-ai"
spec:
  type: ClusterIP
  ports:
  - port: 58585
    targetPort: 58585
    protocol: TCP
    name: http
  selector:
    app: transfer-resource-ai
    release: "transfer-resource-ai"
