apiVersion: v1
kind: Service
metadata:
  name: trsids-svc
spec:
  selector:
    app: ids
  ports:
  - port: 8300
    name: http1
    protocol: TCP
    targetPort: 8300
    nodePort: 8300
  - port: 2005
    name: http2
    protocol: TCP
    targetPort: 2005
    nodePort: 32005
  type: NodePort

