# Source: wcm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-deploy
  labels:
    app: ids
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ids
  template:
    metadata:
      labels:
        app: ids
    spec:
      containers:
        - name: ids
          image: {{ TRSIDSImage }}
          envFrom:
             - configMapRef:
                 name: ids-configmap 
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8300
              protocol: TCP
            - name: sockport
              containerPort: 2005
              protocol: TCP
