apiVersion: v1
kind: ConfigMap
metadata:
  name: ids-configmap
data:
  TRS_IDS_DBPRODUCT: "mysql"
  TRS_IDS_JDBCURL: "jdbc:mysql://mariadb-svc:3306/{{ TRSIDSDBName }}"
  TRS_IDS_DBUSER: "{{ TRSIDSDBUser }}"
  TRS_IDS_DBPASSWD: "{{ TRSIDSPassword }}"
  TRS_IDS_BACKPORT: "2005"
