#将k8s集群外的服务纳入k8s集群中
apiVersion: v1
kind: Endpoints
metadata:
  name: hybase-svc     # 此名字需与service中的metadata.name的值一致
subsets:
  - addresses:
    - ip: {{ HyBaseIP }}
    ports:
    - port: 5555
      protocol: TCP
