#注册服务，不带选择器，所以手动创建一个和改service同名的Endpoint，用户指向后端访问地址
apiVersion: v1
kind: Service
metadata:
  name: hybase-svc    # 此名字需与endpoint中的metadata.name的值一致
spec:
  ports:
  - port: 5555
    targetPort: 5555
    protocol: TCP
