apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperreview-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: paperreview-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ PaperReviewLogPath }}
    server: {{ LogStorageAddr }}

