apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqltool-pvc-account
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: sqltool-pv-account-class
  resources:
     requests:
       storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqltool-pvc-sql
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: sqltool-pv-sql-class
  resources:
     requests:
       storage: 50Gi

