apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqltool-pv-account
spec: 
  capacity: 
    storage: 50Gi
  volumeMode: Filesystem
  storageClassName: sqltool-pv-account-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ SQLAccountPath }}
    server: {{ NFSAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqltool-pv-sql
spec: 
  capacity: 
    storage: 50Gi
  volumeMode: Filesystem
  storageClassName: sqltool-pv-sql-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ SQLFilePath }}
    server: {{ NFSAddr }}

