---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-resource-pvc-log
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: media-resource-pv-log-class
  resources:
     requests:
       storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-resource-pvc-data
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: media-resource-pv-data-class
  resources:
     requests:
       storage: 200Gi
