apiVersion: v1
kind: Service
metadata:
  name: bigdata-access-svc
  labels:
    app: bigdata-access
spec:
  type: ClusterIP
  ports:
  - port: 9016
    targetPort: 9016
    protocol: TCP
    name: http
  selector:
    app: bigdata-access
