apiVersion: v1
kind: PersistentVolume
metadata:
  name: im-server-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: im-server-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ IMServerLogPath }}
    server: {{ NFSAddr }}
