---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcb-sdm-schedule-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: mcb-sdm-schedule-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ MCBSDMScheduleLogPath }}
    server: {{ NFSAddr }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcb-sdm-schedule-pv-data
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: mcb-sdm-schedule-pv-data-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ MCBSDMScheduleDataPath }}
    server: {{ NFSAddr }}

