# Source: interaction-service-center/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service-center-deploy
  labels:
    app: interaction-service-center
    chart: "interaction-service-center-1.0.0"
    release: "interaction-service-center"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interaction-service-center
      release: "interaction-service-center"
  template:
    metadata:
      labels:
        app: interaction-service-center
        release: "interaction-service-center"
    spec:
     # nodeSelector:
     #   kubernetes.io/hostname: 192.168.200.94
      volumes:
      - name: interaction-service-center-pvc-log
        persistentVolumeClaim:
          claimName: interaction-service-center-pvc-log
     # hostAliases:
     # - ip: "10.6.42.1"
     #   hostnames:
     #   - "nginx.nyrb-test.com"
      containers:
      - name: interaction-service-center
        image: {{ InteractionServiceCenterImage }}
        envFrom:
        - configMapRef:
            name: interaction-service-center-configmap
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /TRS/DATA/interaction-service-center/logs
          name: interaction-service-center-pvc-log
        #ports:
        #  - name: http
        #    containerPort: 8090
        #    protocol: TCP
        #livenessProbe:
        #  tcpSocket:
        #    port: http
        #  initialDelaySeconds: 60
        #  periodSeconds: 10
        #readinessProbe:
        #  tcpSocket:
        #    port: http
        #  initialDelaySeconds: 60
        #  periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
