apiVersion: v1
kind: Service
metadata:
  name: newmediaplatform-svc
  labels:
    app: newmediaplatform
spec:
  type: ClusterIP
  ports:
  - port: 9012
    targetPort: 9012
    protocol: TCP
    name: http9012
  selector:
    app: newmediaplatform
