apiVersion: v1
kind: ConfigMap
metadata:
  name: newmediaplatform-configmap
data:
  spring.datasource.url: "jdbc:mysql://mariadb-svc:3306/new_media_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai"
  spring.datasource.username: "newmedia"
  spring.datasource.password: "{{ NewMediaPlatformDBPassword }}"
  spring.redis.nodes: "redis-svc:6379"
  spring.redis.pwd: "{{ TRSRedisPassword }}"
