---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmyimgcenter-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: tmyimgcenter-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ DownImgLogPath }}
    server: {{ LogStorageAddr }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmyimgcenter-pv-data
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: tmyimgcenter-pv-data-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ DownImgDataPath }}
    server: {{ DataStorageAddr }}
