apiVersion: v1
kind: PersistentVolume
metadata:
  name: tenantcenter-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: tenantcenter-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ TenantCenterLogPath }}
    server: {{ LogStorageAddr }}
