# Source: transfer-ifuncun/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-ifuncun-deploy
  labels:
    app: transfer-ifuncun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-ifuncun
  template:
    metadata:
      labels:
        app: transfer-ifuncun
    spec:
     # nodeSelector:
     #   kubernetes.io/hostname: 192.168.200.94
      hostAliases:
      - ip: "192.168.200.99"
        hostnames:
        - "sly.trscd.com.cn"
    #  volumes:
    #  - name: transfer-ifuncun-pvc-log
    #    persistentVolumeClaim:
    #      claimName: transfer-ifuncun-pvc-log
     # hostAliases:
     # - ip: "10.6.42.1"
     #   hostnames:
     #   - "nginx.nyrb-test.com"
      containers:
      - name: transfer-ifuncun
        image: {{ iFuncImage }}
        envFrom:
        - configMapRef:
            name: transfer-ifuncun-configmap
        imagePullPolicy: IfNotPresent
        #volumeMounts:
        #- mountPath: /TRS/DATA/transfer-ifuncun/logs
        #  name: transfer-ifuncun-pvc-log
       # ports:
       #   - name: http
       #     containerPort: 8090
       #     protocol: TCP
       # livenessProbe:
       #   tcpSocket:
       #     port: http
       #   initialDelaySeconds: 60
       #   periodSeconds: 10
       # readinessProbe:
       #   tcpSocket:
       #     port: http
       #   initialDelaySeconds: 60
       #   periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
