apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer-ifuncun-configmap
data:
  # 类属性键；每一个键都映射到一个简单的值
# 大数据应用公有变量
  spring.cloud.nacos.config.namespace: "8953ca45-4cfb-469a-bc55-7e3bce569994"
  spring.cloud.nacos.config.server-addr: "nacos-svc:8848"
  spring.cloud.nacos.discovery.server-addr: "nacos-svc:8848"
  hybase.database.url: "hybase-svc"
  hybase.database.port: "5555"
  hybase.database.user: "admin"
  hybase.database.password: "trsadmin"
  spring.kafka.bootstrap-servers: "kafka-svc"
  spring.redis.masterName: "mymaster"
  spring.redis.nodes: "redis-ha-announce-0:26379,redis-ha-announce-1:26379,redis-ha-announce-2:26379"
  spring.redis.pwd: "{{ RedisHAPassword }}"
  ckm.database.url: "http://ckm6-svc:8001"
  ckm.database.user: "admin"
  ckm.database.password: "trsadmin"
  
  isWork: "false"
  isHeart: "false"
  systemName: "cd.transfer-ifuncun.test"
