# Source: timing-scheduler/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timing-scheduler-deploy
  labels:
    app: timing-scheduler
    chart: "timing-scheduler-1.0.0"
    release: "timing-scheduler"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timing-scheduler
      release: "timing-scheduler"
  template:
    metadata:
      labels:
        app: timing-scheduler
        release: "timing-scheduler"
    spec:
     # nodeSelector:
     #   kubernetes.io/hostname: 192.168.200.94
      volumes:
      - name: timing-scheduler-pvc-log
        persistentVolumeClaim:
          claimName: timing-scheduler-pvc-log
     # hostAliases:
     # - ip: "10.6.42.1"
     #   hostnames:
     #   - "nginx.nyrb-test.com"
      containers:
      - name: timing-scheduler
        image: {{ TimingSchedulerImage }}
        envFrom:
        - configMapRef:
            name: timing-scheduler-configmap
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /TRS/DATA/timing-scheduler/logs
          name: timing-scheduler-pvc-log
       # ports:
       #   - name: http
       #     containerPort: 8090
       #     protocol: TCP
       # livenessProbe:
       #   tcpSocket:
       #     port: http
       #   initialDelaySeconds: 60
       #   periodSeconds: 10
       # readinessProbe:
       #   tcpSocket:
       #     port: http
       #   initialDelaySeconds: 60
       #   periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
