# Source: mcb-message/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcb-message-deploy
  labels:
    app: mcb-message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcb-message
  template:
    metadata:
      labels:
        app: mcb-message
    spec:
     # nodeSelector:
     #   kubernetes.io/hostname: 192.168.200.94
      volumes:
      - name: mcb-message-pvc-log
        persistentVolumeClaim:
          claimName: mcb-message-pvc-log
      - name: mcb-message-pvc-data
        persistentVolumeClaim:
          claimName: mcb-message-pvc-data
     # hostAliases:
     # - ip: "10.6.42.1"
     #   hostnames:
     #   - "nginx.nyrb-test.com"
      containers:
      - name: mcb-message
        image: {{ MCBMessageImage }}
        envFrom:
        - configMapRef:
            name: mcb-message-configmap
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /TRS/LOGS/messageCenter
          name: mcb-message-pvc-log
        - mountPath: /TRS/DATA/MESSAGE/dispatchData/messagefiles
          name: mcb-message-pvc-data
       # ports:
       #   - name: http
       #     containerPort: 8090
       #     protocol: TCP
       # livenessProbe:
       #   tcpSocket:
       #     port: http
       #   initialDelaySeconds: 60
       #   periodSeconds: 10
       # readinessProbe:
       #   tcpSocket:
       #     port: http
       #   initialDelaySeconds: 60
       #   periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
