---
# Source: mcb-message/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mcb-message-svc
  labels:
    app: mcb-message
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: mcb-message
