apiVersion: v1
kind: ConfigMap
metadata:
  name: gather-consumer-configmap
data:
  # 类属性键；每一个键都映射到一个简单的值
# 大数据应用公有变量
  spring.cloud.nacos.config.namespace: "8953ca45-4cfb-469a-bc55-7e3bce569994"
  spring.cloud.nacos.config.server-addr: "nacos-svc:8848"
  spring.cloud.nacos.discovery.server-addr: "nacos-svc:8848"
  hybase.database.url: "hybase-svc"
  hybase.database.port: "8888"
  hybase.database.user: "admin"
  hybase.database.password: "Trs@admin123"
  spring.kafka.bootstrap-servers: "kafka-svc:9092"
  spring.redis.masterName: ""
  spring.redis.nodes: "redis-svc:6379"
  spring.redis.pwd: "{{ TRSRedisPassword }}"
  ckm.database.url: "ckm-svc"
  ckm.database.user: "admin"
  ckm.database.password: "trsadmin"
  isWork: "true"
  isHreat: "true"
  systemName: "slytest.gather-consumer.dev"
