apiVersion: v1
kind: Service
metadata:
  name: gather-consumer-svc
  labels:
    app: gather-consumer
spec:
  type: ClusterIP
  ports:
    - port: 8788
      targetPort: 8788
      protocol: TCP
      name: http8788
    - port: 18100
      targetPort: 18100
      protocol: TCP
      name: http18100
    - port: 18001
      targetPort: 18001
      protocol: TCP
      name: http18001
    - port: 18000
      targetPort: 18000
      protocol: TCP
      name: http18000
  selector:
    app: gather-consumer
