apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-mysql-pv-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nacos-mysql-pv-data-class
  local:
    path: {{ MysqlDataPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ MysqlHostIP }}
