apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-mysql-pvc-data
spec:
  accessModes:
     - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nacos-mysql-pv-data-class
  resources:
     requests:
       storage: 20Gi
