apiVersion: v1
kind: PersistentVolume
metadata:
  name: dshare-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: dshare-pv-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ DshareLogPath }}
    server: {{ NFSAddr }}
