apiVersion: v1
kind: PersistentVolume
metadata:
  name: interaction-service-center-pv-log
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: interaction-service-center-pv-log-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ InteractionServiceCenterLogPath }}
    server: {{ LogStorageAddr }}
