apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmy-decision-center-pv-log
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: tmy-decision-center-pv-log-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ TmyDecisionCenterLogPath }}
    server: {{ NFSAddr }}
