apiVersion: v1
kind: PersistentVolume
metadata:
  name: webcollection-pv-log
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: webcollection-pv-log-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ WebCollectionLogPath }}
    server: {{ NFSAddr }}
