apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-svc
spec:
  ports:
  - name: port-1
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: port-2
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq-ha
    release: rabbitmq-ha
  type: ClusterIP