apiVersion: v1
kind: PersistentVolume
metadata:
  name: bigdata-access-pv-log
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  storageClassName: bigdata-access-log-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ BigdataAccessLogPath }}
    server: {{ LogStorageAddr }}

