apiVersion: v1
kind: PersistentVolume
metadata:
  name: timing-scheduler-pv-log
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: timing-scheduler-pv-log-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ TimingSchedulerLogPath }}
    server: {{ LogStorageAddr }}
