# Source: mcb-pm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcb-pm-deploy
  labels:
    app: mcb-pm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcb-pm
  template:
    metadata:
      labels:
        app: mcb-pm
    spec:
     # nodeSelector:
     #   kubernetes.io/hostname: 192.168.200.94
      volumes:
      - name: mcb-pm-pvc-log
        persistentVolumeClaim:
          claimName: mcb-pm-pvc-log
      - name: mcb-pm-pvc-data
        persistentVolumeClaim:
          claimName: mcb-pm-pvc-data
     # hostAliases:
     # - ip: "10.6.42.1"
     #   hostnames:
     #   - "nginx.nyrb-test.com"
      containers:
      - name: mcb-pm
        image: registry.cn-hangzhou.aliyuncs.com/trssly/pm:v4
        envFrom:
        - configMapRef:
            name: mcb-pm-configmap
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /TRS/LOGS/pm
          name: mcb-pm-pvc-log
        - mountPath: /TRS/DATA/PM/files
          name: mcb-pm-pvc-data
        ports:
          - name: http
            containerPort: 8095
            protocol: TCP
#        livenessProbe:
#          tcpSocket:
#            port: http
#          initialDelaySeconds: 60
#          periodSeconds: 10
#        readinessProbe:
#          tcpSocket:
#            port: http
#          initialDelaySeconds: 60
#          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
