apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-data
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  storageClassName: mariadb-pv-data-class
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ MariaDBDataPath }}
    server: {{ NFSAddr }}
