#将k8s集群外的服务纳入k8s集群中
apiVersion: v1
kind: Endpoints
metadata:
  name: mariadb-svc
subsets:
  - addresses:
    - ip: {{ MariaDBHostIP }}
    ports:
    - port: {{ MariaDBHostPort }}
      protocol: TCP
