apiVersion: v1
kind: Service
metadata:
  labels:
    run: mariadb
  name: mariadb-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 33006
  selector:
    run: mariadb
  type: NodePort
