apiVersion: v1
kind: PersistentVolume
metadata:
  name: transfer-video-pv-log
spec: 
  capacity: 
    storage: 200Gi
  volumeMode: Filesystem
  storageClassName: transfer-video-pv-log-class
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ TransferVideoLogPath }}
    server: {{ NFSAddr }}
