apiVersion: v1
kind: ConfigMap
metadata:
  name: media-gateway-configmap
data:
  # 类属性键；每一个键都映射到一个简单的值
# 大数据应用公有变量
  spring.datasource.url: "jdbc:mysql://mariadb-svc:3306/media_gateway?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8"
  spring.datasource.username: "media_gateway"
  spring.datasource.password: "{{ MediaGatewayDBPassword }}"
  spring.cloud.nacos.config.namespace: "8953ca45-4cfb-469a-bc55-7e3bce569994"
  spring.cloud.nacos.config.server-addr: "nacos-svc:8848"
  spring.cloud.nacos.discovery.server-addr: "nacos-svc:8848"
  hybase.database.url: ""
  hybase.database.port: ""
  hybase.database.user: ""
  hybase.database.password: ""
  spring.kafka.bootstrap-servers: ""
  spring.redis.masterName: ""
  spring.redis.nodes: "redis-svc:6379"
  spring.redis.pwd: "{{ TRSRedisPassword }}"
  ckm.database.url: "http://ckm6-svc:8001"
  ckm.database.user: "admin"
  ckm.database.password: "trsadmin"
  isWork: "true"
  isHreat: "true"
  systemName: "slytest.media-gateway.dev"
