apiVersion: v1
kind: Service
metadata:
  name: mediagateway-svc
  labels:
    app: media-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: media-gateway
