apiVersion: v1
kind: ConfigMap
metadata:
  name: im-server-configmap
data:
  # 类属性键；每一个键都映射到一个简单的值
## 大数据应用公有变量
#  spring.datasource.primary.url: "jdbc:mysql://mariadb-svc:3306/mty_im_server?useUnicode=true&characterEncoding=utf-8&useSSL=false"
#  spring.datasource.primary.username: "mtyim_server"
#  spring.datasource.primary.password: "Trs@admin123"
#  spring.datasource.second.url: "jdbc:mysql://mariadb-svc:3306/mty_wcm?useUnicode=true&characterEncoding=utf-8&useSSL=false"
#  spring.datasource.second.username: "mtywcm"
#  spring.datasource.second.password: "Trs@admin123"
#  spring.redis.host: "redis-svc"
#  spring.redis.port: "6379"
#  spring.redis.password: "Trs@admin123"
#  spring.rabbitmq.host: "rabbitmq-svc"
#  spring.rabbitmq.port: "5672"
#  spring.rabbitmq.username: "admin"
#  spring.rabbitmq.password: "Trs@admin123"
  spring.datasource.url: "jdbc:mysql://mariadb-svc:3306/im_server?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8"
  spring.datasource.username: "im_server"
  spring.datasource.password: "{{ IMServerDBPassword }}"
  isHeart: "false"
  isWork: "false"
  tencent.im.apiHost: "https://console.tim.qq.com/"
  tencent.im.sdkAppId: ""
  tencent.im.secretKey: ""
  tencent.im.expireTime: "604800"
  tencent.im.adminUser: ""
