apiVersion: v1
kind: Service
metadata:
  name: im-server-svc
  labels:
    app: im-server
spec:
  type: ClusterIP
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
      name: http8989
  selector:
    app: im-server
